### ISSUE TITLE
Set to HUB theme

### ISSUE THREAD

**Issue by jf990** [bgmapp/P4TP-Timeline#2]
Update timeline CSS to HUB theme:

![Hub Theme](https://user-images.githubusercontent.com/13524488/90449208-d10c0500-e09b-11ea-8c71-276bf47a30b7.png)

**Comment by debalin** [comment]
The initial work for this has been done as viewed in https://bgmapp.github.io/P4TP-Timeline/timeline-proto/timeline-horizontal.html and https://bgmapp.github.io/P4TP-Timeline/timeline-proto/timeline-vertical.html. Separate enhancements can be added as needed.
